trigger:
- master

variables:

  azureSubscription: '264b9899-fe1b-430b-9509-2154878d5774'

  webAppName: 'lxp'

  environmentName: 'DEV'

  vmImageName: 'ubantu-latest'

  stages:
  - stage: Build
    displayName: Build stage
    job:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)

      steps:
      - task: NodeInstalation@0
        inputs:
          versionspec: ''
        displayName: 'Install Node.js' 
      - script: |
          npm install
          npm run build --prod   
          displayName: 'npm install, build and test'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: suceeded()
  jobs:
  - deployment: Deploy
  displayName: Deploy
  environment: $(environmentName)
  pool:
    vmImage: $(vmImageName)
  strategy:
    runOnce:
      deploy:
       steps:
       - task: AzureWenApp@1
         displayName: 'Azure web App Deploy: lxpfrontend'
         inputs:
           azureSubscription: $(azureSubscription)
           appType: webAppLinux
           appName: $(webAppName)
           runtimeStack: 'NODE|10.10'
           package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
           startUpCommand: 'npm run start'



- task: Npm@1
  inputs:
    command: 'install'