apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportaldevkaush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportaldevkaush
  template:
    metadata:
      labels:
        app: webportaldevkaush
    spec:
      containers:
        - name: webportaldevkaush
          image: lxpacrazure.azurecr.io/webportaldevkaush:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret