apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccdev
  template:
    metadata:
      labels:
        app: ccdev
    spec:
      containers:
        - name: ccdev
          image: lxpacrazure.azurecr.io/ccdev:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret