apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportal
  template:
    metadata:
      labels:
        app: webportal
    spec:
      containers:
        - name: webportal
          image: lxpacrazure.azurecr.io/webportal$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret2