apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal_dev_kaush
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportal_dev_kaush
  template:
    metadata:
      labels:
        app: webportal_dev_kaush
    spec:
      containers:
        - name: webportal_dev_kaush
          image: lxpacrazure.azurecr.io/webportal_dev_kaush:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret