apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportal2
  template:
    metadata:
      labels:
        app: webportal2
    spec:
      containers:
        - name: webportal2
          image: lxpdevqa.azurecr.io/webportal2:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret