apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportalpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportalpt
  template:
    metadata:
      labels:
        app: webportalpt
    spec:
      containers:
        - name: webportal
          image: lxpdevqa.azurecr.io/webportalpt:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret