apiVersion: apps/v1
kind: Deployment
metadata:
  name: webportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webportal
  template:
    metadata:
      labels:
        app: webportal
    spec:
      containers:
        - name: webportal
          image: lxpacrazure.azurecr.io/webportal
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret2