apiVersion: apps/v1
kind: Deployment
metadata:
  name: collegeconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collegeconnect
  template:
    metadata:
      labels:
        app: collegeconnect
    spec:
      containers:
        - name: webportal
          image: lxpacrazure.azurecr.io/collegeconnect:$tag
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: mysecret